name: Perl Modules&FHEM Unittests
on: 
  push:
    branches:
    paths:
      - 'FHEM/**'
      - 't/**'
      - 'cpanfile'
      - '.github/workflows/prove.yml'

  schedule:
    - cron: '47 16 * * 1,5'

jobs:
  libModTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.24', '5.28','5.32' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1.20.1
      with:
        perl-version: ${{ matrix.perl }}
        install-modules-with: cpanm
        install-modules-args: --no-interactive -v --installdeps

    - name: Install FHEM via debian nightly 
      uses: fhem/setup-fhem@v1.0.1

    - name: change ownership of /opt/fhem
      run: |
        sudo chown -R --reference=cpanfile /opt/fhem

    - name: run prove fhem testsuite ${{ matrix.perl }}
      run: |
        cp -R ${GITHUB_WORKSPACE}/FHEM/* ${FHEM_DIR}/FHEM/
        prove --exec 'perl -MDevel::Cover=-silent,1 fhem.pl -t' -I FHEM -r -vv -r ${GITHUB_WORKSPACE}/t/FHEM/
      working-directory: /opt/fhem/
      env:
        FHEM_DIR: /opt/fhem
    - name: Create clover report
      working-directory: /opt/fhem/
      run: cover -report clover
    - uses: codecov/codecov-action@v3.1.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: /opt/fhem/cover_db/clover.xml
        flags: unittests,fhem,modules
        name: fhem (testscripts) ${{ matrix.perl }} 

   