name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: update controls files
      run: |
      env:
        rm -f controls_rsl.txt
        while IFS= read -r -d '' FILE
        do
           TIME=$(git log --pretty=format:%cd -n 1 --date=format:%Y-%m-%d\ %H:%M -- "$FILE")
           FILESIZE=$(stat -c%s "$FILE")
           FILE=$(echo "$FILE"  | cut -c 3-)
           printf "UPD %s %-7d %s\n" "$TIME" "$FILESIZE" "$FILE"  >> controls_rsl.txt
        done <   <(find ./FHEM -maxdepth 2 \( -name "*.pm" \) -print0 | sort -z -g)
    - name: update CHANGED
      run: |
        echo $(date +"%Y-%m-%d") >> CHANGED
        echo " - $(git log -1 --pretty=%B)" >> CHANGED
    - name: git commit back
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "update@github-actions.com"
        git config --global user.name "Updater"
        git config --global push.default simple
        git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${REPOSITORY}.git
        git add controls_rsl.txt  && git commit controls_rsl.txt  -m "test" || true
        git push origin HEAD:${INPUT_BRANCH}     
